site_name: alex
nav:
  - Home: index.md
  - python: 
    - Ввод-вывод данных: python.md
    - Условный оператор: python4.md 
    - Модуль math: python5.md 
    - Типы данных: python6.md  
    - Циклы: python7.md 
    - Гипотеза Эйлера: python3.md 
    - Строковый тип данных: python2.md
  - fabius: 
    - GETTIME: fabius.md
    - ZIPTOXML: fabzip.md
    - RP_00_41_43_GHC: fab_rp.md
    - ZAO: fab_zao.md
  - fsbu25:
    - ФСБУ 25: fsbu25.md
    - 01: fsbu2501.md
  - about:  
    - about: about/about.md
    - alpine: about/alpine.md
    - arch:   about/arch.md
  - docker: docker.md
  - kde: kde.md
  - lxde: lxde.md
  - ubuntu: ubuntu.md
  - psql: psql.md
  - vagrant.md
  - gh:  
    - gh: gh/gh.md  
  - vb:  
    - vb: vb/vb.md  


