site_name: alex
nav:
  - Home: index.md
  - python: 
    - Ввод-вывод данных: python.md
    - Условный оператор: python4.md 
    - Модуль math: python5.md 
    - Типы данных: python6.md  
    - Циклы: python7.md 
    - Гипотеза Эйлера: python3.md 
  - fabius: fabius.md
  - About: about.md
